// Hindcast replay: a real past landslide replayed hour by hour through the live risk engine, from archived data
// (client/public/data/hindcast/event.json, generated by ml/build_hindcast.mjs). A timeline slider moves through the
// hours; the callout says honestly how early the system would have flagged the area — or that it would not have.
import { lazy, Suspense, useEffect, useMemo, useRef, useState, type PointerEvent as RPointerEvent } from 'react';
import { Link } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { ArrowLeft, Pause, Play, SkipForward, History, ExternalLink, CloudRain, Droplets, Info } from 'lucide-react';
import type { Driver, Level } from '../api/types';
import { AppHeader } from '../components/AppHeader';
import { RiskBadge } from '../components/RiskBadge';
import { groupOf } from '../components/RiskMix';
import { driverPlain } from '../lib/factors';
import { levelVar } from '../lib/risk';
import { dateTimeIST, isDeva, timeIST } from '../lib/format';

const HindcastMap = lazy(() => import('../components/HindcastMap'));

type HcHour = { t: string; score: number; level: Level; rain_mm: number; rain_24h: number; rain_72h: number; rain_fc_24h: number; saturation: number; drivers: Driver[] };
type Hindcast = {
  event: {
    id: string; title_en: string; title_hi: string; time_ist: string; time_note_en: string; time_note_hi: string;
    place_en: string; place_hi: string; state: string; lat: number; lng: number; accuracy_km: number; deaths: number;
    trigger_en: string; trigger_hi: string; sources: { title: string; url: string }[];
  };
  station: { id: string; name_en: string; name_hi: string; lat: number; lng: number; distance_km: number; note_en: string; note_hi: string };
  thresholds: { moderate: number; high: number; critical: number };
  method: Record<string, string>;
  quakes: { mag: number; time: string; distance_km: number; place: string | null }[];
  first: { moderate: string | null; high: string | null; critical: string | null };
  lead_hours: { moderate: number | null; high: number | null; critical: number | null };
  at_event: { t: string; score: number; level: Level } | null;
  hours: HcHour[];
};

const iso = (t: string) => new Date(`${t}:00+05:30`).toISOString();
const cap = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);

export default function HindcastPage() {
  const { t, i18n } = useTranslation();
  const lang = i18n.language;
  const deva = isDeva(lang);
  const [data, setData] = useState<Hindcast | null>(null);
  const [failed, setFailed] = useState(false);
  const [idx, setIdx] = useState(0);
  const [playing, setPlaying] = useState(false);

  useEffect(() => {
    fetch('/data/hindcast/event.json').then((r) => (r.ok ? r.json() : Promise.reject(r.status)))
      .then((d: Hindcast) => { setData(d); setIdx(Math.max(0, d.hours.findIndex((h) => h.t >= (d.first.moderate || d.event.time_ist)) - 12)); })
      .catch(() => setFailed(true));
  }, []);
  useEffect(() => {
    if (!playing || !data) return;
    const id = setInterval(() => setIdx((i) => { if (i >= data.hours.length - 1) { setPlaying(false); return i; } return i + 1; }), 140);
    return () => clearInterval(id);
  }, [playing, data]);

  if (failed) return <Shell><p className="card p-5">{t('hindcast.load_error')}</p></Shell>;
  if (!data) return <Shell><div className="space-y-4"><div className="skeleton h-24 rounded-card" /><div className="skeleton h-72 rounded-card" /></div></Shell>;

  const ev = data.event;
  const h = data.hours[idx];
  const eventIdx = data.hours.findIndex((x) => x.t === ev.time_ist);
  const hoursToEvent = Math.round((new Date(iso(ev.time_ist)).getTime() - new Date(iso(h.t)).getTime()) / 3600000);
  const flagged: Level | null = data.first.critical ? 'critical' : data.first.high ? 'high' : data.first.moderate ? 'moderate' : null;
  const leadH = flagged ? data.lead_hours[flagged as 'moderate' | 'high' | 'critical'] : null;
  const flaggedAt = flagged ? data.first[flagged as 'moderate' | 'high' | 'critical'] : null;
  const alarm = flagged === 'high' || flagged === 'critical';

  return (
    <Shell>
      <Link to="/" className="inline-flex items-center gap-1 text-sm font-semibold text-brand hover:underline"><ArrowLeft size={15} aria-hidden />{t('notfound.home')}</Link>
      <header className="mt-2">
        <p className="inline-flex items-center gap-1.5 text-xs font-bold uppercase tracking-[0.14em] text-muted"><History size={14} aria-hidden />{t('hindcast.eyebrow')}</p>
        <h1 className="mt-1 text-[1.8rem] sm:text-[2.1rem] font-bold leading-tight">{deva ? ev.title_hi : ev.title_en}</h1>
        <ul className="mt-3 flex flex-wrap gap-2 text-sm">
          <li className="rounded-pill border border-line px-3 py-1 font-semibold">{dateTimeIST(iso(ev.time_ist), lang)} · {deva ? ev.time_note_hi : ev.time_note_en}</li>
          <li className="rounded-pill border border-line px-3 py-1">{deva ? ev.place_hi : ev.place_en}, {ev.state}</li>
          <li className="rounded-pill border border-line px-3 py-1">{t('hindcast.deaths', { n: ev.deaths })}</li>
          <li className="rounded-pill border border-line px-3 py-1">{deva ? ev.trigger_hi : ev.trigger_en}</li>
        </ul>
      </header>

      {/* The answer, stated plainly — including when it is "not early enough". */}
      <section className="card mt-5 overflow-hidden" aria-labelledby="hc-callout" style={{ borderLeft: `6px solid ${flagged ? levelVar(flagged) : 'rgb(var(--muted))'}` }}>
        <div className="p-5">
          <h2 id="hc-callout" className="text-xl sm:text-2xl font-bold leading-snug">
            {flagged
              ? t('hindcast.callout', { hours: leadH, level: t(`levels.${flagged}`), place: deva ? data.station.name_hi : data.station.name_en })
              : t('hindcast.callout_none', { place: deva ? data.station.name_hi : data.station.name_en })}
          </h2>
          {flagged && flaggedAt && <p className="mt-1 text-muted">{t('hindcast.callout_from', { time: dateTimeIST(iso(flaggedAt), lang) })}</p>}
          <p className="mt-3 font-semibold">{alarm ? t('hindcast.alarm_yes') : t('hindcast.alarm_no')}</p>
          {data.at_event && (
            <p className="mt-1 text-sm text-muted">{t('hindcast.at_event', { score: data.at_event.score.toFixed(2), high: data.thresholds.high.toFixed(2), level: t(`levels.${data.at_event.level}`) })}</p>
          )}
        </div>
      </section>

      <div className="mt-5 grid gap-5 lg:grid-cols-[minmax(0,1fr)_360px] lg:items-start">
        <section className="card p-4 sm:p-5" aria-labelledby="hc-timeline">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <h2 id="hc-timeline" className="text-lg font-bold">{t('hindcast.timeline')}</h2>
            <div className="flex gap-2">
              <button type="button" className="btn-secondary !min-h-[40px] px-3 text-sm" onClick={() => { if (idx >= data.hours.length - 1) setIdx(0); setPlaying((p) => !p); }} aria-pressed={playing}>
                {playing ? <Pause size={16} aria-hidden /> : <Play size={16} aria-hidden />}{playing ? t('hindcast.pause') : t('hindcast.play')}
              </button>
              {eventIdx >= 0 && (
                <button type="button" className="btn-ghost !min-h-[40px] px-3 text-sm" onClick={() => { setPlaying(false); setIdx(eventIdx); }}>
                  <SkipForward size={16} aria-hidden />{t('hindcast.to_event')}
                </button>
              )}
            </div>
          </div>
          <ScoreChart data={data} idx={idx} onPick={(i) => { setPlaying(false); setIdx(i); }} />
          <label htmlFor="hc-slider" className="sr-only">{t('hindcast.slider')}</label>
          <input id="hc-slider" type="range" min={0} max={data.hours.length - 1} value={idx} onChange={(e) => { setPlaying(false); setIdx(Number(e.target.value)); }}
            className="mt-3 w-full accent-[rgb(var(--brand))]" aria-valuetext={dateTimeIST(iso(h.t), lang)} />
          <div className="mt-1 flex justify-between text-xs text-muted">
            <span>{dateTimeIST(iso(data.hours[0].t), lang)}</span>
            <span>{dateTimeIST(iso(data.hours[data.hours.length - 1].t), lang)}</span>
          </div>
        </section>

        <div className="space-y-5">
          <section className="card overflow-hidden" aria-live="polite" aria-labelledby="hc-now">
            <div className="p-4" style={{ borderTop: `6px solid ${levelVar(h.level)}` }}>
              <p className="text-xs font-semibold uppercase tracking-wide text-muted">{hoursToEvent > 0 ? t('hindcast.before', { n: hoursToEvent }) : hoursToEvent === 0 ? t('hindcast.at_slide') : t('hindcast.after', { n: -hoursToEvent })}</p>
              <h2 id="hc-now" className="mt-0.5 text-lg font-bold">{dateTimeIST(iso(h.t), lang)}</h2>
              <div className="mt-2 flex items-center gap-2">
                <RiskBadge level={h.level} />
                <span className="font-mono text-lg tabular-nums">{h.score.toFixed(2)}</span>
              </div>
              <dl className="mt-3 grid grid-cols-3 gap-2 text-center">
                <div className="rounded-lg bg-surface-2 p-2"><dt className="text-[11px] text-muted">{t('hindcast.rain_hour')}</dt><dd className="font-bold tabular-nums">{h.rain_mm} <span className="text-xs font-normal">mm</span></dd></div>
                <div className="rounded-lg bg-surface-2 p-2"><dt className="text-[11px] text-muted">{t('hindcast.rain_24h')}</dt><dd className="font-bold tabular-nums">{Math.round(h.rain_24h)} <span className="text-xs font-normal">mm</span></dd></div>
                <div className="rounded-lg bg-surface-2 p-2"><dt className="text-[11px] text-muted">{t('hindcast.soil')}</dt><dd className="font-bold tabular-nums">{Math.round(h.saturation * 100)}%</dd></div>
              </dl>
              <h3 className="mt-3 text-sm font-bold">{t('why.reasons')}</h3>
              <ul className="mt-1.5 space-y-1.5">
                {h.drivers.map((d) => {
                  const g = groupOf(d.key);
                  return (
                    <li key={d.key} className="flex items-center gap-2 text-sm">
                      {g && <g.icon size={15} style={{ color: g.color }} aria-hidden />}
                      <span className="flex-1">{cap(driverPlain(d.key, lang))}</span>
                      <span className="font-mono text-xs text-muted">{d.contribution}%</span>
                    </li>
                  );
                })}
              </ul>
            </div>
          </section>
          <section className="card overflow-hidden" aria-label={t('hindcast.map')}>
            <div className="relative isolate h-64 lg:h-[280px]">
              <Suspense fallback={<div className="skeleton h-full w-full" />}>
                <HindcastMap site={[ev.lat, ev.lng]} station={[data.station.lat, data.station.lng]} level={h.level}
                  siteLabel={t('hindcast.site')} stationLabel={t('hindcast.station', { place: deva ? data.station.name_hi : data.station.name_en, km: data.station.distance_km })} />
              </Suspense>
            </div>
            <p className="p-3 text-xs text-muted">{deva ? data.station.note_hi : data.station.note_en}</p>
          </section>
        </div>
      </div>

      <section className="card mt-5 p-5" aria-labelledby="hc-method">
        <h2 id="hc-method" className="flex items-center gap-2 text-lg font-bold"><Info size={18} className="text-brand" aria-hidden />{t('hindcast.method_title')}</h2>
        <p className="mt-2">{t('hindcast.method_intro')}</p>
        <dl className="mt-3 grid gap-2 sm:grid-cols-2">
          {(['engine', 'weather', 'forecast', 'imd', 'seismic', 'terrain'] as const).filter((k) => data.method[k]).map((k) => (
            <div key={k} className="rounded-lg bg-surface-2 p-3">
              <dt className="text-xs font-bold uppercase tracking-wide text-muted">{t(`hindcast.m_${k}`)}</dt>
              <dd className="mt-0.5 text-sm">{data.method[k]}</dd>
            </div>
          ))}
        </dl>
        <h3 className="mt-4 font-bold">{t('hindcast.limits_title')}</h3>
        <ul className="mt-1 list-disc space-y-1 pl-5 text-sm">
          <li>{t('hindcast.limit_point', { km: data.station.distance_km })}</li>
          <li>{t('hindcast.limit_rain')}</li>
          <li>{t('hindcast.limit_terrain')}</li>
          <li>{t('hindcast.limit_one')}</li>
        </ul>
        <h3 className="mt-4 font-bold">{t('hindcast.sources')}</h3>
        <ul className="mt-1 space-y-1 text-sm">
          {ev.sources.map((s) => (
            <li key={s.url}><a href={s.url} target="_blank" rel="noopener noreferrer" className="inline-flex items-start gap-1 text-brand hover:underline"><ExternalLink size={13} className="mt-1 shrink-0" aria-hidden />{s.title}</a></li>
          ))}
        </ul>
        <p className="mt-3 text-xs text-muted">{t('hindcast.data_file')}</p>
      </section>
    </Shell>
  );
}

function Shell({ children }: { children: React.ReactNode }) {
  return (
    <>
      <AppHeader />
      <main id="main" className="mx-auto max-w-6xl px-4 py-6 page-enter">{children}</main>
    </>
  );
}

/** Score over time with level bands, hourly rain underneath, the slide time and the selected hour. Tap or drag to move. */
function ScoreChart({ data, idx, onPick }: { data: Hindcast; idx: number; onPick: (i: number) => void }) {
  const { t, i18n } = useTranslation();
  const box = useRef<HTMLDivElement>(null);
  const n = data.hours.length;
  const W = 1000; const H = 220; const RH = 60;
  const yMax = Math.max(0.8, ...data.hours.map((h) => h.score + 0.05));
  const x = (i: number) => (i / Math.max(1, n - 1)) * W;
  const y = (s: number) => H - (s / yMax) * H;
  const maxRain = Math.max(1, ...data.hours.map((h) => h.rain_mm));
  const eventIdx = data.hours.findIndex((h) => h.t === data.event.time_ist);
  const modIdx = data.first.moderate ? data.hours.findIndex((h) => h.t === data.first.moderate) : -1;
  const th = data.thresholds;
  const pct = (i: number) => `${(i / Math.max(1, n - 1)) * 100}%`;
  const segs = useMemo(() => data.hours.slice(1).map((h, k) => ({ x1: x(k), y1: y(data.hours[k].score), x2: x(k + 1), y2: y(h.score), level: h.level })), [data]); // eslint-disable-line react-hooks/exhaustive-deps
  const dragging = useRef(false);
  const pick = (e: RPointerEvent) => {
    const r = box.current!.getBoundingClientRect();
    onPick(Math.round(Math.min(1, Math.max(0, (e.clientX - r.left) / r.width)) * (n - 1)));
  };
  const bands: [number, number, Level][] = [[th.moderate, th.high, 'moderate'], [th.high, th.critical, 'high'], [th.critical, yMax, 'critical']];

  return (
    <div className="mt-3">
      <div ref={box} className="relative touch-none select-none cursor-ew-resize"
        onPointerDown={(e) => { dragging.current = true; (e.target as Element).setPointerCapture?.(e.pointerId); pick(e); }}
        onPointerMove={(e) => { if (dragging.current) pick(e); }} onPointerUp={() => { dragging.current = false; }}>
        <svg viewBox={`0 0 ${W} ${H + RH + 8}`} preserveAspectRatio="none" className="block h-[230px] w-full sm:h-[260px]" role="img"
          aria-label={t('hindcast.chart_label')}>
          {bands.map(([a, b, lv]) => (
            <rect key={lv} x={0} y={y(Math.min(b, yMax))} width={W} height={y(a) - y(Math.min(b, yMax))} fill={levelVar(lv)} opacity={0.1} />
          ))}
          {[th.moderate, th.high, th.critical].filter((v) => v < yMax).map((v) => (
            <line key={v} x1={0} x2={W} y1={y(v)} y2={y(v)} stroke="currentColor" strokeOpacity={0.25} strokeDasharray="6 6" vectorEffect="non-scaling-stroke" />
          ))}
          {segs.map((s, k) => (
            <line key={k} x1={s.x1} y1={s.y1} x2={s.x2} y2={s.y2} stroke={levelVar(s.level)} strokeWidth={3} strokeLinecap="round" vectorEffect="non-scaling-stroke" />
          ))}
          {data.hours.map((h, i) => (
            <rect key={h.t} x={x(i) - W / n / 2.6} width={W / n / 1.3} y={H + 8 + RH - (h.rain_mm / maxRain) * RH} height={(h.rain_mm / maxRain) * RH} fill="#4b9fd5" opacity={0.75} />
          ))}
          {modIdx >= 0 && <line x1={x(modIdx)} x2={x(modIdx)} y1={0} y2={H} stroke={levelVar('moderate')} strokeWidth={2} strokeDasharray="3 5" vectorEffect="non-scaling-stroke" />}
          {eventIdx >= 0 && <line x1={x(eventIdx)} x2={x(eventIdx)} y1={0} y2={H + RH + 8} stroke="#d7263d" strokeWidth={2.5} vectorEffect="non-scaling-stroke" />}
          <line x1={x(idx)} x2={x(idx)} y1={0} y2={H + RH + 8} stroke="currentColor" strokeWidth={1.5} vectorEffect="non-scaling-stroke" />
        </svg>
        {/* Dot and labels in HTML so they don't stretch with the chart. */}
        <span className="pointer-events-none absolute h-3.5 w-3.5 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-white shadow" aria-hidden
          style={{ left: pct(idx), top: `${(y(data.hours[idx].score) / (H + RH + 8)) * 100}%`, background: levelVar(data.hours[idx].level) }} />
        {[['moderate', th.moderate], ['high', th.high], ['critical', th.critical]].filter(([, v]) => (v as number) < yMax).map(([lv, v]) => (
          <span key={lv as string} className="pointer-events-none absolute left-1 -translate-y-full text-[10px] font-semibold text-muted" style={{ top: `${(y(v as number) / (H + RH + 8)) * 100}%` }}>
            {t(`levels.${lv}`)} {(v as number).toFixed(2)}
          </span>
        ))}
        {eventIdx >= 0 && (
          <span className="pointer-events-none absolute top-0 -translate-x-full whitespace-nowrap rounded bg-[#d7263d] px-1.5 py-0.5 text-[10px] font-bold text-white" style={{ left: pct(eventIdx) }}>
            {t('hindcast.slide_marker', { time: timeIST(iso(data.event.time_ist), i18n.language) })}
          </span>
        )}
        {modIdx >= 0 && data.lead_hours.moderate != null && (
          <span className="pointer-events-none absolute top-6 -translate-x-full whitespace-nowrap rounded px-1.5 py-0.5 text-[10px] font-bold" style={{ left: pct(modIdx), background: levelVar('moderate'), color: 'rgb(var(--risk-moderate-ink))' }}>
            {t('hindcast.mod_marker', { n: data.lead_hours.moderate })}
          </span>
        )}
        <span className="pointer-events-none absolute left-1 flex items-center gap-1 text-[10px] font-semibold text-muted" style={{ top: `${((H + 10) / (H + RH + 8)) * 100}%` }}>
          <CloudRain size={11} aria-hidden />{t('hindcast.rain_axis')}
        </span>
      </div>
      <p className="mt-2 flex items-center gap-1.5 text-xs text-muted"><Droplets size={12} aria-hidden />{t('hindcast.chart_hint', { time: dateTimeIST(iso(data.hours[idx].t), i18n.language) })}</p>
    </div>
  );
}

